#![forbid(unsafe_code)]
#![doc = include_str!("../README.md")]

use anyhow::{Context, Result};
use bitvec::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};
use std::hash::Hash;
use std::io::{Cursor, Read};
use std::marker::PhantomData;
use std::ops::RangeInclusive;
use std::sync::Arc;

mod bool;
mod bytes;
mod datetime;
mod filter_mask;
mod float;
pub mod float_round;
mod json_value;
pub(crate) mod lazy_msgpack;
mod lazy_reader;
mod map;
pub(crate) mod number;
mod option;
pub(crate) mod pco_util;
mod string;
mod timeline;
mod tuple;
mod typed_filter;
mod uuid;
mod vec;
mod vec_number;

pub use filter_mask::FilterMask;
pub use lazy_reader::LazyReader;
pub use number::{CoercibleNumber, NumberReader, NumberWriter, RangeCoercibleNumber};
pub use pco_pack_derive::PcoPack;
pub use timeline::Timeline;
pub use typed_filter::{BoolFilter, DateTimeFilter, F64Filter, I64Filter, StringFilter, UuidFilter};

// Re-exports for the derive macro, which generates code referencing these via `pco_pack::...`.
pub use ahash;
pub use anyhow;
pub use bitvec;
pub use chrono;
pub use half;
pub use rmp_serde;
pub use serde;
pub use serde_json;
pub use zstd;

#[cfg(test)]
mod test;

/// Struct-level columnar packing with chunked serialization and optimized filtering.
///
/// Implemented by `#[derive(PcoPack)]`. Before serialization: sort by `timestamp`
/// field (if configured), group by `index` fields, then split each group into
/// chunks of at most `CHUNK_SIZE` rows.
pub trait PcoPack: PcoFilter + Sized {
    /// Maximum rows per chunk. Larger chunks improve compression but use more memory
    /// during columnar conversion. 32,768 is a power of 2 to avoid excess Vec capacity.
    const CHUNK_SIZE: usize = 32_768;

    /// Decompression state for reading columnar data back into row structs.
    type Reader;

    /// Chunked struct with uncompressed metadata (index, timestamp bounds) and compressed payload columns.
    type Chunk: Clone + Serialize + for<'de> Deserialize<'de>;

    /// Typed filter struct generated by the derive macro.
    type Filter: TryInto<serde_json::Value>;

    fn serialize(data: Vec<Self>) -> Result<Vec<u8>> {
        Self::to_bytes(&PcoPack::write(data)?)
    }

    fn deserialize(bytes: &[u8]) -> Result<Vec<Self>> {
        PcoPack::read(Self::from_bytes(bytes)?)
    }

    fn write(data: Vec<Self>) -> Result<Vec<Self::Chunk>>;

    fn read(chunks: Vec<Self::Chunk>) -> Result<Vec<Self>>;

    fn to_bytes(chunks: &[Self::Chunk]) -> Result<Vec<u8>>;

    fn from_bytes(bytes: &[u8]) -> Result<Vec<Self::Chunk>>;

    fn filter<T>(chunks: &[Self::Chunk], query: T, fields: &[&str]) -> Result<Vec<Self>>
    where
        T: TryInto<serde_json::Value>,
        <T as TryInto<serde_json::Value>>::Error: Into<anyhow::Error>,
    {
        Self::filter_value(chunks, &query.try_into().map_err(Into::into)?, fields)
    }

    fn filter_bytes<T>(bytes: &[u8], query: T, fields: &[&str]) -> Result<Vec<Self>>
    where
        T: TryInto<serde_json::Value>,
        <T as TryInto<serde_json::Value>>::Error: Into<anyhow::Error>,
    {
        Self::filter(&Self::from_bytes(bytes)?, query, fields)
    }

    /// Internal method that takes a JSON value directly. Used by filter/filter_bytes after conversion.
    fn filter_value(chunks: &[Self::Chunk], query: &serde_json::Value, fields: &[&str]) -> Result<Vec<Self>>;

    /// Merge query-derived fields with explicitly requested fields, validating all are known.
    ///
    /// Extracts top-level field names from the JSON query (splitting on '.'), merges them
    /// with the user-provided `fields` list without duplicates, and validates that:
    /// - All query fields exist in this type's schema
    /// - No requested field contains a nested path ('.')
    /// - All requested fields exist in this type's schema
    fn resolve_fields(query: &serde_json::Value, fields: &[&str]) -> Result<Vec<&'static str>>;
}

/// Basic columnar write and read for a single type.
pub trait PcoSerde: Sized {
    type Writer: Default;
    type Reader: Clone;

    fn write(data: Vec<Self>, float_round: u32, time_round: chrono::Duration) -> Result<Vec<u8>>;

    fn read(src: &mut Cursor<&[u8]>, float_round: u32, time_round: chrono::Duration) -> Result<Self::Reader>;

    fn validate_bounds(reader: &mut Self::Reader) -> Result<Option<usize>>;

    /// Get the element at `index`. Iteration always moves forward (never backward),
    /// so lazy decompressors may advance their internal cursor without resetting.
    fn get(reader: &mut Self::Reader, index: usize) -> Result<Option<Self>>;
}

/// Fallback deserialization for types that need to read raw msgpack bytes directly.
/// Returns the same type as PcoSerde::read(), enabling fallback data to be used with
/// get() and validate_bounds() calls transparently.
pub trait FallbackReader {
    fn read_fallback(raw: &[u8]) -> anyhow::Result<Self>
    where
        Self: Sized;
}

/// Filter support for PcoSerde and PcoPack types.
pub trait PcoFilter: PcoSerde {
    fn filter_bulk(reader: &mut Self::Reader, field: usize, filter: &Filter, matches: &mut FilterMask) -> Result<()>;

    fn filter_nested(
        reader: &mut Self::Reader, path: &[usize], filter: &Filter, matches: &mut FilterMask,
    ) -> Result<()>;

    fn filter_match(value: &Self, filter: &Filter) -> bool;

    fn filter_step(reader: &mut Self::Reader, path: &[usize], filter: &Filter, matches: &mut FilterMask) -> Result<()> {
        if path.len() > 1 {
            Self::filter_nested(reader, path, filter, matches)
        } else {
            Self::filter_bulk(reader, path[0], filter, matches)
        }
    }

    fn resolve_filter(path: &str, json: &serde_json::Value) -> Result<ResolvedFilter>;

    fn resolve_query(query: &serde_json::Value) -> Result<Vec<ResolvedFilter>> {
        match query {
            serde_json::Value::Object(map) => {
                let mut plans = Vec::with_capacity(map.len());
                for (field_name, raw_value) in map {
                    plans.push(Self::resolve_filter(field_name, raw_value)?);
                }
                plans.iter_mut().for_each(|p| p.filter.normalize());
                Ok(plans)
            }
            _ => Err(::anyhow::anyhow!("Query must be a JSON object with field-name keys")),
        }
    }
}

/// A resolved filter with an absolute path down the struct tree.
///
/// Produced by `PcoFilter::resolve_filter`.
#[derive(Clone, Debug)]
pub struct ResolvedFilter {
    /// Maps the user-provided string to fast numeric indexes ("a.b" -> [0, 2]).
    pub path: Vec<usize>,
    /// Filter value resolved to the correct data type to avoid type conversions in the hot loop.
    pub filter: Filter,
}

#[derive(Clone, Debug)]
pub enum Filter {
    I64(i64),
    F64(f64),
    String(String),
    Uuid(::uuid::Uuid),
    Bool(bool),
    Json(serde_json::Value),
    Bytes(Vec<u8>),
    Range(RangeInclusive<i64>),
    FloatRange(RangeInclusive<f64>),
    InclusionI64(Vec<i64>),
    InclusionF64(Vec<f64>),
    InclusionString(Vec<String>),
    InclusionUuid(Vec<::uuid::Uuid>),
    InclusionBool(Vec<bool>),
}

impl Filter {
    /// Downgrade single-element filters to exact matches for faster hot-loop comparison.
    fn normalize(&mut self) {
        match self {
            Filter::Range(r) if r.start() == r.end() => {
                *self = Filter::I64(*r.start());
            }
            Filter::FloatRange(r) if r.start() == r.end() => {
                *self = Filter::F64(*r.start());
            }
            Filter::InclusionI64(v) if v.len() == 1 => {
                let x = v.remove(0);
                *self = Filter::I64(x);
            }
            Filter::InclusionF64(v) if v.len() == 1 => {
                let x = v.remove(0);
                *self = Filter::F64(x);
            }
            Filter::InclusionString(v) if v.len() == 1 => {
                let s = v.remove(0);
                *self = Filter::String(s);
            }
            Filter::InclusionUuid(v) if v.len() == 1 => {
                let u = v.remove(0);
                *self = Filter::Uuid(u);
            }
            Filter::InclusionBool(v) if v.len() == 1 => {
                let b = v.remove(0);
                *self = Filter::Bool(b);
            }
            _ => {}
        }
    }
}

/// Dispatch trait for `Vec<T>`, serializing inner elements via `T::write()`
/// for optimal per-field compression.
pub trait VecPackable: PcoSerde {
    type VecWriter: Default;
    type VecReader;

    fn pack_vec(data: Vec<Self>, writer: &mut Self::VecWriter);

    fn write_vec(
        writer: Self::VecWriter, float_round: u32, time_round: chrono::Duration, out: &mut Vec<u8>,
    ) -> Result<()>;

    fn read_vec(src: &mut Cursor<&[u8]>, float_round: u32, time_round: chrono::Duration) -> Result<Self::VecReader>;

    fn validate_vec_bounds(reader: &Self::VecReader) -> Result<Option<usize>>;

    fn get_vec(reader: &mut Self::VecReader, index: usize) -> Result<Option<Vec<Self>>>;

    fn filter_vec(reader: &Self::VecReader, filter: &Filter, matches: &mut FilterMask) -> Result<()>;

    fn filter_vec_nested(
        reader: &mut Self::VecReader, path: &[usize], filter: &Filter, matches: &mut FilterMask,
    ) -> Result<()>;

    fn filter_vec_match(value: &Self, filter: &Filter) -> bool;
}
