//! Per-type filter enums for typed Filter structs generated by #[derive(PcoPack)]
use super::*;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum I64Filter {
    Equal(i64),
    Inclusion(Vec<i64>),
    Range { start: i64, end: i64 },
}

impl I64Filter {
    /// Returns the value if this filter is an exact match.
    pub fn exact(&self) -> Option<i64> {
        match self {
            I64Filter::Equal(v) => Some(*v),
            _ => None,
        }
    }

    /// Returns the list of values if this filter is an inclusion filter.
    pub fn inclusion(&self) -> Option<Vec<i64>> {
        match self {
            I64Filter::Inclusion(v) => Some(v.clone()),
            _ => None,
        }
    }

    /// Returns the range if this filter is a range filter.
    pub fn range(&self) -> Option<RangeInclusive<i64>> {
        match self {
            I64Filter::Range { start, end } => Some(*start..=*end),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum F64Filter {
    Equal(f64),
    Inclusion(Vec<f64>),
    Range { start: f64, end: f64 },
}

impl F64Filter {
    /// Returns the value if this filter is an exact match.
    pub fn exact(&self) -> Option<f64> {
        match self {
            F64Filter::Equal(v) => Some(*v),
            _ => None,
        }
    }

    /// Returns the list of values if this filter is an inclusion filter.
    pub fn inclusion(&self) -> Option<Vec<f64>> {
        match self {
            F64Filter::Inclusion(v) => Some(v.clone()),
            _ => None,
        }
    }

    /// Returns the range if this filter is a range filter.
    pub fn range(&self) -> Option<RangeInclusive<f64>> {
        match self {
            F64Filter::Range { start, end } => Some(*start..=*end),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StringFilter {
    Equal(String),
    Inclusion(Vec<String>),
}

impl StringFilter {
    /// Returns the value if this filter is an exact match.
    pub fn exact(&self) -> Option<String> {
        match self {
            StringFilter::Equal(v) => Some(v.clone()),
            _ => None,
        }
    }

    /// Returns the list of values if this filter is an inclusion filter.
    pub fn inclusion(&self) -> Option<Vec<String>> {
        match self {
            StringFilter::Inclusion(v) => Some(v.clone()),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BoolFilter {
    Equal(bool),
    Inclusion(Vec<bool>),
}

impl BoolFilter {
    /// Returns the value if this filter is an exact match.
    pub fn exact(&self) -> Option<bool> {
        match self {
            BoolFilter::Equal(v) => Some(*v),
            _ => None,
        }
    }

    /// Returns the list of values if this filter is an inclusion filter.
    pub fn inclusion(&self) -> Option<Vec<bool>> {
        match self {
            BoolFilter::Inclusion(v) => Some(v.clone()),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UuidFilter {
    Equal(::uuid::Uuid),
    Inclusion(Vec<::uuid::Uuid>),
}

impl UuidFilter {
    /// Returns the value if this filter is an exact match.
    pub fn exact(&self) -> Option<::uuid::Uuid> {
        match self {
            UuidFilter::Equal(v) => Some(*v),
            _ => None,
        }
    }

    /// Returns the list of values if this filter is an inclusion filter.
    pub fn inclusion(&self) -> Option<Vec<::uuid::Uuid>> {
        match self {
            UuidFilter::Inclusion(v) => Some(v.clone()),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DateTimeFilter {
    Equal(::chrono::DateTime<::chrono::Utc>),
    Inclusion(Vec<::chrono::DateTime<::chrono::Utc>>),
    Range { start: ::chrono::DateTime<::chrono::Utc>, end: ::chrono::DateTime<::chrono::Utc> },
}

impl DateTimeFilter {
    /// Returns the value if this filter is an exact match.
    pub fn exact(&self) -> Option<::chrono::DateTime<::chrono::Utc>> {
        match self {
            DateTimeFilter::Equal(v) => Some(*v),
            _ => None,
        }
    }

    /// Returns the list of values if this filter is an inclusion filter.
    pub fn inclusion(&self) -> Option<Vec<::chrono::DateTime<::chrono::Utc>>> {
        match self {
            DateTimeFilter::Inclusion(v) => Some(v.clone()),
            _ => None,
        }
    }

    /// Returns the range if this filter is a range filter.
    pub fn range(&self) -> Option<RangeInclusive<::chrono::DateTime<::chrono::Utc>>> {
        match self {
            DateTimeFilter::Range { start, end } => Some(*start..=*end),
            _ => None,
        }
    }

    /// Returns the start and end timestamps if this filter is a range.
    ///
    /// Returns an error for `Equal` or `Inclusion` variants. Use pattern matching
    /// instead if you need to handle those cases.
    pub fn range_bounds(
        &self,
    ) -> anyhow::Result<(::chrono::DateTime<::chrono::Utc>, ::chrono::DateTime<::chrono::Utc>)> {
        match self {
            DateTimeFilter::Range { start, end } => Ok((*start, *end)),
            _ => Err(anyhow::anyhow!("Timestamp filter is not a range")),
        }
    }
}

impl From<i64> for I64Filter {
    fn from(v: i64) -> Self {
        I64Filter::Equal(v)
    }
}

impl From<u64> for I64Filter {
    fn from(v: u64) -> Self {
        I64Filter::Equal(v as i64)
    }
}

impl From<i32> for I64Filter {
    fn from(v: i32) -> Self {
        I64Filter::Equal(v as i64)
    }
}

impl From<u32> for I64Filter {
    fn from(v: u32) -> Self {
        I64Filter::Equal(v as i64)
    }
}

impl From<i16> for I64Filter {
    fn from(v: i16) -> Self {
        I64Filter::Equal(v as i64)
    }
}

impl From<u16> for I64Filter {
    fn from(v: u16) -> Self {
        I64Filter::Equal(v as i64)
    }
}

impl From<i8> for I64Filter {
    fn from(v: i8) -> Self {
        I64Filter::Equal(v as i64)
    }
}

impl From<u8> for I64Filter {
    fn from(v: u8) -> Self {
        I64Filter::Equal(v as i64)
    }
}

impl<const N: usize> From<[i64; N]> for I64Filter {
    fn from(arr: [i64; N]) -> Self {
        I64Filter::Inclusion(Vec::from(arr))
    }
}

impl<const N: usize> From<[u64; N]> for I64Filter {
    fn from(arr: [u64; N]) -> Self {
        I64Filter::Inclusion(arr.iter().map(|&v| v as i64).collect())
    }
}

impl<const N: usize> From<[i32; N]> for I64Filter {
    fn from(arr: [i32; N]) -> Self {
        I64Filter::Inclusion(arr.iter().map(|&v| v as i64).collect())
    }
}

impl<const N: usize> From<[u32; N]> for I64Filter {
    fn from(arr: [u32; N]) -> Self {
        I64Filter::Inclusion(arr.iter().map(|&v| v as i64).collect())
    }
}

impl<const N: usize> From<[i16; N]> for I64Filter {
    fn from(arr: [i16; N]) -> Self {
        I64Filter::Inclusion(arr.iter().map(|&v| v as i64).collect())
    }
}

impl<const N: usize> From<[u16; N]> for I64Filter {
    fn from(arr: [u16; N]) -> Self {
        I64Filter::Inclusion(arr.iter().map(|&v| v as i64).collect())
    }
}

impl<const N: usize> From<[i8; N]> for I64Filter {
    fn from(arr: [i8; N]) -> Self {
        I64Filter::Inclusion(arr.iter().map(|&v| v as i64).collect())
    }
}

impl<const N: usize> From<[u8; N]> for I64Filter {
    fn from(arr: [u8; N]) -> Self {
        I64Filter::Inclusion(arr.iter().map(|&v| v as i64).collect())
    }
}

impl From<Vec<i64>> for I64Filter {
    fn from(v: Vec<i64>) -> Self {
        I64Filter::Inclusion(v)
    }
}

impl<'a> From<&'a Vec<i64>> for I64Filter {
    fn from(v: &'a Vec<i64>) -> Self {
        I64Filter::Inclusion(v.clone())
    }
}

impl From<Vec<u64>> for I64Filter {
    fn from(v: Vec<u64>) -> Self {
        I64Filter::Inclusion(v.into_iter().map(|x| x as i64).collect())
    }
}

impl<'a> From<&'a Vec<u64>> for I64Filter {
    fn from(v: &'a Vec<u64>) -> Self {
        I64Filter::Inclusion(v.iter().map(|&x| x as i64).collect())
    }
}

impl From<Vec<i32>> for I64Filter {
    fn from(v: Vec<i32>) -> Self {
        I64Filter::Inclusion(v.into_iter().map(|x| x as i64).collect())
    }
}

impl<'a> From<&'a Vec<i32>> for I64Filter {
    fn from(v: &'a Vec<i32>) -> Self {
        I64Filter::Inclusion(v.iter().map(|&x| x as i64).collect())
    }
}

impl From<Vec<u32>> for I64Filter {
    fn from(v: Vec<u32>) -> Self {
        I64Filter::Inclusion(v.into_iter().map(|x| x as i64).collect())
    }
}

impl<'a> From<&'a Vec<u32>> for I64Filter {
    fn from(v: &'a Vec<u32>) -> Self {
        I64Filter::Inclusion(v.iter().map(|&x| x as i64).collect())
    }
}

impl From<Vec<i16>> for I64Filter {
    fn from(v: Vec<i16>) -> Self {
        I64Filter::Inclusion(v.into_iter().map(|x| x as i64).collect())
    }
}

impl<'a> From<&'a Vec<i16>> for I64Filter {
    fn from(v: &'a Vec<i16>) -> Self {
        I64Filter::Inclusion(v.iter().map(|&x| x as i64).collect())
    }
}

impl From<Vec<u16>> for I64Filter {
    fn from(v: Vec<u16>) -> Self {
        I64Filter::Inclusion(v.into_iter().map(|x| x as i64).collect())
    }
}

impl<'a> From<&'a Vec<u16>> for I64Filter {
    fn from(v: &'a Vec<u16>) -> Self {
        I64Filter::Inclusion(v.iter().map(|&x| x as i64).collect())
    }
}

impl From<Vec<i8>> for I64Filter {
    fn from(v: Vec<i8>) -> Self {
        I64Filter::Inclusion(v.into_iter().map(|x| x as i64).collect())
    }
}

impl<'a> From<&'a Vec<i8>> for I64Filter {
    fn from(v: &'a Vec<i8>) -> Self {
        I64Filter::Inclusion(v.iter().map(|&x| x as i64).collect())
    }
}

impl From<Vec<u8>> for I64Filter {
    fn from(v: Vec<u8>) -> Self {
        I64Filter::Inclusion(v.into_iter().map(|x| x as i64).collect())
    }
}

impl<'a> From<&'a Vec<u8>> for I64Filter {
    fn from(v: &'a Vec<u8>) -> Self {
        I64Filter::Inclusion(v.iter().map(|&x| x as i64).collect())
    }
}

impl<'a> From<&'a [i64]> for I64Filter {
    fn from(slice: &'a [i64]) -> Self {
        I64Filter::Inclusion(slice.to_vec())
    }
}

impl<'a> From<&'a [u64]> for I64Filter {
    fn from(slice: &'a [u64]) -> Self {
        I64Filter::Inclusion(slice.iter().map(|&v| v as i64).collect())
    }
}

impl<'a> From<&'a [i32]> for I64Filter {
    fn from(slice: &'a [i32]) -> Self {
        I64Filter::Inclusion(slice.iter().map(|&v| v as i64).collect())
    }
}

impl<'a> From<&'a [u32]> for I64Filter {
    fn from(slice: &'a [u32]) -> Self {
        I64Filter::Inclusion(slice.iter().map(|&v| v as i64).collect())
    }
}

impl<'a> From<&'a [i16]> for I64Filter {
    fn from(slice: &'a [i16]) -> Self {
        I64Filter::Inclusion(slice.iter().map(|&v| v as i64).collect())
    }
}

impl<'a> From<&'a [u16]> for I64Filter {
    fn from(slice: &'a [u16]) -> Self {
        I64Filter::Inclusion(slice.iter().map(|&v| v as i64).collect())
    }
}

impl<'a> From<&'a [i8]> for I64Filter {
    fn from(slice: &'a [i8]) -> Self {
        I64Filter::Inclusion(slice.iter().map(|&v| v as i64).collect())
    }
}

impl<'a> From<&'a [u8]> for I64Filter {
    fn from(slice: &'a [u8]) -> Self {
        I64Filter::Inclusion(slice.iter().map(|&v| v as i64).collect())
    }
}

impl From<RangeInclusive<i64>> for I64Filter {
    fn from(r: RangeInclusive<i64>) -> Self {
        I64Filter::Range { start: *r.start(), end: *r.end() }
    }
}

impl From<RangeInclusive<u64>> for I64Filter {
    fn from(r: RangeInclusive<u64>) -> Self {
        I64Filter::Range { start: *r.start() as i64, end: *r.end() as i64 }
    }
}

impl From<RangeInclusive<i32>> for I64Filter {
    fn from(r: RangeInclusive<i32>) -> Self {
        I64Filter::Range { start: *r.start() as i64, end: *r.end() as i64 }
    }
}

impl From<RangeInclusive<u32>> for I64Filter {
    fn from(r: RangeInclusive<u32>) -> Self {
        I64Filter::Range { start: *r.start() as i64, end: *r.end() as i64 }
    }
}

impl From<RangeInclusive<i16>> for I64Filter {
    fn from(r: RangeInclusive<i16>) -> Self {
        I64Filter::Range { start: *r.start() as i64, end: *r.end() as i64 }
    }
}

impl From<RangeInclusive<u16>> for I64Filter {
    fn from(r: RangeInclusive<u16>) -> Self {
        I64Filter::Range { start: *r.start() as i64, end: *r.end() as i64 }
    }
}

impl From<RangeInclusive<i8>> for I64Filter {
    fn from(r: RangeInclusive<i8>) -> Self {
        I64Filter::Range { start: *r.start() as i64, end: *r.end() as i64 }
    }
}

impl From<RangeInclusive<u8>> for I64Filter {
    fn from(r: RangeInclusive<u8>) -> Self {
        I64Filter::Range { start: *r.start() as i64, end: *r.end() as i64 }
    }
}

impl From<f64> for F64Filter {
    fn from(v: f64) -> Self {
        F64Filter::Equal(v)
    }
}

impl From<f32> for F64Filter {
    fn from(v: f32) -> Self {
        F64Filter::Equal(v as f64)
    }
}

impl<const N: usize> From<[f64; N]> for F64Filter {
    fn from(arr: [f64; N]) -> Self {
        F64Filter::Inclusion(Vec::from(arr))
    }
}

impl<const N: usize> From<[f32; N]> for F64Filter {
    fn from(arr: [f32; N]) -> Self {
        F64Filter::Inclusion(arr.iter().map(|&v| v as f64).collect())
    }
}

impl From<Vec<f64>> for F64Filter {
    fn from(v: Vec<f64>) -> Self {
        F64Filter::Inclusion(v)
    }
}

impl<'a> From<&'a Vec<f64>> for F64Filter {
    fn from(v: &'a Vec<f64>) -> Self {
        F64Filter::Inclusion(v.clone())
    }
}

impl From<Vec<f32>> for F64Filter {
    fn from(v: Vec<f32>) -> Self {
        F64Filter::Inclusion(v.into_iter().map(|x| x as f64).collect())
    }
}

impl<'a> From<&'a Vec<f32>> for F64Filter {
    fn from(v: &'a Vec<f32>) -> Self {
        F64Filter::Inclusion(v.iter().map(|&x| x as f64).collect())
    }
}

impl<'a> From<&'a [f64]> for F64Filter {
    fn from(slice: &'a [f64]) -> Self {
        F64Filter::Inclusion(slice.to_vec())
    }
}

impl<'a> From<&'a [f32]> for F64Filter {
    fn from(slice: &'a [f32]) -> Self {
        F64Filter::Inclusion(slice.iter().map(|&v| v as f64).collect())
    }
}

impl From<RangeInclusive<f64>> for F64Filter {
    fn from(r: RangeInclusive<f64>) -> Self {
        F64Filter::Range { start: *r.start(), end: *r.end() }
    }
}

impl From<RangeInclusive<f32>> for F64Filter {
    fn from(r: RangeInclusive<f32>) -> Self {
        F64Filter::Range { start: *r.start() as f64, end: *r.end() as f64 }
    }
}

impl From<String> for StringFilter {
    fn from(v: String) -> Self {
        StringFilter::Equal(v)
    }
}

impl<'a> From<&'a str> for StringFilter {
    fn from(s: &'a str) -> Self {
        StringFilter::Equal(s.to_string())
    }
}

impl<const N: usize> From<[String; N]> for StringFilter {
    fn from(arr: [String; N]) -> Self {
        StringFilter::Inclusion(Vec::from(arr))
    }
}

impl<const N: usize> From<[&str; N]> for StringFilter {
    fn from(arr: [&str; N]) -> Self {
        StringFilter::Inclusion(arr.iter().map(|s| s.to_string()).collect())
    }
}

impl From<Vec<String>> for StringFilter {
    fn from(v: Vec<String>) -> Self {
        StringFilter::Inclusion(v)
    }
}

impl<'a> From<&'a Vec<String>> for StringFilter {
    fn from(v: &'a Vec<String>) -> Self {
        StringFilter::Inclusion(v.clone())
    }
}

impl<'a> From<&'a [&str]> for StringFilter {
    fn from(slice: &'a [&str]) -> Self {
        StringFilter::Inclusion(slice.iter().map(|s| s.to_string()).collect())
    }
}

impl From<bool> for BoolFilter {
    fn from(v: bool) -> Self {
        BoolFilter::Equal(v)
    }
}

impl<const N: usize> From<[bool; N]> for BoolFilter {
    fn from(arr: [bool; N]) -> Self {
        BoolFilter::Inclusion(Vec::from(arr))
    }
}

impl From<Vec<bool>> for BoolFilter {
    fn from(v: Vec<bool>) -> Self {
        BoolFilter::Inclusion(v)
    }
}

impl<'a> From<&'a Vec<bool>> for BoolFilter {
    fn from(v: &'a Vec<bool>) -> Self {
        BoolFilter::Inclusion(v.clone())
    }
}

impl<'a> From<&'a [bool]> for BoolFilter {
    fn from(slice: &'a [bool]) -> Self {
        BoolFilter::Inclusion(slice.to_vec())
    }
}

impl From<::uuid::Uuid> for UuidFilter {
    fn from(v: ::uuid::Uuid) -> Self {
        UuidFilter::Equal(v)
    }
}

impl<const N: usize> From<[::uuid::Uuid; N]> for UuidFilter {
    fn from(arr: [::uuid::Uuid; N]) -> Self {
        UuidFilter::Inclusion(Vec::from(arr))
    }
}

impl From<Vec<::uuid::Uuid>> for UuidFilter {
    fn from(v: Vec<::uuid::Uuid>) -> Self {
        UuidFilter::Inclusion(v)
    }
}

impl<'a> From<&'a Vec<::uuid::Uuid>> for UuidFilter {
    fn from(v: &'a Vec<::uuid::Uuid>) -> Self {
        UuidFilter::Inclusion(v.clone())
    }
}

impl<'a> From<&'a [::uuid::Uuid]> for UuidFilter {
    fn from(slice: &'a [::uuid::Uuid]) -> Self {
        UuidFilter::Inclusion(slice.to_vec())
    }
}

impl From<::chrono::DateTime<::chrono::Utc>> for DateTimeFilter {
    fn from(v: ::chrono::DateTime<::chrono::Utc>) -> Self {
        DateTimeFilter::Equal(v)
    }
}

impl<const N: usize> From<[::chrono::DateTime<::chrono::Utc>; N]> for DateTimeFilter {
    fn from(arr: [::chrono::DateTime<::chrono::Utc>; N]) -> Self {
        DateTimeFilter::Inclusion(Vec::from(arr))
    }
}

impl From<Vec<::chrono::DateTime<::chrono::Utc>>> for DateTimeFilter {
    fn from(v: Vec<::chrono::DateTime<::chrono::Utc>>) -> Self {
        DateTimeFilter::Inclusion(v)
    }
}

impl<'a> From<&'a Vec<::chrono::DateTime<::chrono::Utc>>> for DateTimeFilter {
    fn from(v: &'a Vec<::chrono::DateTime<::chrono::Utc>>) -> Self {
        DateTimeFilter::Inclusion(v.clone())
    }
}

impl<'a> From<&'a [::chrono::DateTime<::chrono::Utc>]> for DateTimeFilter {
    fn from(slice: &'a [::chrono::DateTime<::chrono::Utc>]) -> Self {
        DateTimeFilter::Inclusion(slice.to_vec())
    }
}

impl From<RangeInclusive<::chrono::DateTime<::chrono::Utc>>> for DateTimeFilter {
    fn from(r: RangeInclusive<::chrono::DateTime<::chrono::Utc>>) -> Self {
        DateTimeFilter::Range { start: *r.start(), end: *r.end() }
    }
}
